# -*- coding: utf-8 -*-

SPEC_PACK = {
    "META": {
        "name": "Emergency contract mediation simulator",
        "version": "5.1.2",
        "mode": "as-is frozen spec",
        "entrypoint": "python <file>.py [CLI_ARGS...]",
    },
    "G": {
        "goal": "現行挙動を、再実装・回帰テスト可能な外部契約として固定する。"
    },
    "O": {
        "out_of_scope": [
            "実コードの改変提案",
            "未記載要件の推測",
            "運用手順書の作成",
        ]
    },
    "I": {
        "input_form": "単一 Python スクリプト",
        "execution": "CLI",
        "command": "python <file>.py [CLI_ARGS...]",
        "example": "python emergency_contract_mediation_simulator_v5_1_2.py --help",
    },
    "U": {
        "output_type": "仕様要約",
        "scope": [
            "CLI引数",
            "状態遷移",
            "永続ファイル(ARL/index/counter/trust/grants/eval)",
            "results dict 構造",
        ],
        "example_observation": "results['hitl_queue']['counts']['by_state']['CONTRACT_EFFECTIVE']",
    },
    "E": {
        "language": "Python 3.x",
        "os": "UNKNOWN",
        "dependencies": [
            "argparse",
            "csv",
            "hashlib",
            "hmac",
            "json",
            "os",
            "random",
            "re",
            "time",
            "uuid",
            "collections",
            "dataclasses",
            "datetime",
            "pathlib",
            "typing",
        ],
        "external_api": "NONE",
        "execution": "CLI",
    },
    "D": {
        "persistent_files": [
            "model_trust_store.json",
            "model_grants.json",
            "eval_state.json",
            "incident_counter.txt",
            "incident_index.jsonl",
            "*.arl.jsonl",
        ],
        "optional_outputs": [
            "results JSON",
            "queue JSON",
            "queue CSV",
        ],
        "db": "NONE",
    },
    "S": {
        "persistent_state": {
            "trust": {
                "path": "model_trust_store.json",
                "load": "run_simulation() start",
                "save": "run_simulation() end",
                "schema": {
                    "trust_score": "float",
                    "approval_streak": "int",
                    "cooldown_until": "str | None",
                    "compliance_score": "float",
                    "coaching_sessions": "int",
                },
            },
            "grants": {
                "path": "model_grants.json",
                "load": "find_valid_grant() -> load_grants()",
                "save": "ensure_default_grant_exists() may save_grants()",
                "schema": {
                    "root": {"grants": "list[Grant]"},
                    "Grant": {
                        "grant_id": "str",
                        "scenario": "str",
                        "location_id": "str",
                        "expires_at": "ISO-8601 str",
                        "issued_by": "str",
                    },
                },
            },
            "eval": {
                "path": "eval_state.json",
                "load": "run_simulation() start",
                "save": "run_simulation() end",
                "schema": {
                    "clean_completion_count": "int",
                    "multiplier": "derived float",
                },
            },
            "incident_counter": {
                "path": "{arl_out_dir}/incident_counter.txt",
                "format": "plain integer",
                "update_rule": "issue_incident_id(): read current(default=1), write current+1, return INC#%06d",
            },
            "incident_index": {
                "path": "{arl_out_dir}/incident_index.jsonl",
                "format": "JSONL append",
                "record_schema": {
                    "incident_id": "str",
                    "run_id": "str",
                    "created_at": "ISO-8601 str",
                    "primary_reason_code": "str",
                    "final_state": "str",
                    "sealed": "bool",
                    "arl_path": "str",
                    "sim_version": "str",
                },
            },
        },
        "side_effects": [
            "trust/grants/eval/counter/index/arl の作成・更新",
            "デフォルトは aggregation-only",
            "abnormal run のみ ARL 永続化可能",
            "reset=True 時は trust/grants/eval を削除し得る",
        ],
    },
    "C": {
        "invariants": [
            "sealed は ethics_gate / acc_gate のみ設定可",
            "relativity_gate は sealed=False 固定",
            "デフォルトは aggregation-only",
            "abnormal run のみ ARL 永続化し HMAC chain を維持",
            "fabricate-rate + seed により決定的再現をサポート",
        ]
    },
    "T": [
        {
            "id": "T1",
            "given": "fabricate=false かつ有効 grant あり",
            "when": "run_simulation を実行",
            "then": [
                "run は CONTRACT_EFFECTIVE に到達する",
                "results['hitl_queue']['counts']['by_state']['CONTRACT_EFFECTIVE'] に集計される",
            ],
        },
        {
            "id": "T2",
            "given": "fabricate=true",
            "when": "simulate_run を実行",
            "then": [
                "evidence_gate が fabricated evidence を検出して失敗する",
                "その後 ethics_gate が STOPPED / sealed=True を発行する",
                "最終状態は state=STOPPED かつ sealed=True になる",
            ],
        },
        {
            "id": "T3",
            "given": "--save-arl-on-abnormal と --arl-out-dir 指定",
            "when": "abnormal run が発生",
            "then": [
                "{incident_id}__{run_id}.arl.jsonl が作成される",
                "incident_index.jsonl が更新される",
                "incident_counter.txt が更新される",
            ],
        },
        {
            "id": "T4",
            "given": "keep_runs=false",
            "when": "大量 runs を実行",
            "then": [
                "results は counters/hitl_queue/runs_sample 中心になる",
                "per-run 全件保持を避ける",
            ],
        },
    ],
    "R": {
        "known_risks": [
            "Trust/Eval/Grant 永続化によりテスト相互干渉しやすい",
            "full_context_n > 0 かつ大量 runs では候補バッファでメモリ増加しやすい",
            "demo key は真正な秘密保持を提供しない",
        ]
    },
    "CLI": {
        "description": "Emergency contract mediation simulator (v5.1.2)",
        "args": [
            {"name": "--runs", "type": "int", "default": 100, "notes": "runs<=0 は 1 に補正"},
            {"name": "--fabricate", "type": "flag", "default": False},
            {"name": "--fabricate-rate", "type": "float | None", "default": None, "validation": "0.0 <= x <= 1.0"},
            {"name": "--seed", "type": "int | None", "default": None},
            {"name": "--no-reset", "type": "flag", "default": False},
            {"name": "--no-reset-eval", "type": "flag", "default": False},
            {"name": "--save-arl-on-abnormal", "type": "flag", "default": False},
            {"name": "--arl-out-dir", "type": "str", "default": ""},
            {"name": "--max-arl-files", "type": "int", "default": 1000},
            {"name": "--full-context-n", "type": "int", "default": 0},
            {"name": "--key-mode", "type": "str", "default": "demo", "choices": ["demo", "file", "env"]},
            {"name": "--key-file", "type": "str", "default": ""},
            {"name": "--key-env", "type": "str", "default": ""},
            {"name": "--keep-runs", "type": "flag", "default": False},
            {"name": "--queue-max-items", "type": "int", "default": 0},
            {"name": "--sample-runs", "type": "int", "default": 5},
            {"name": "--results-json", "type": "str", "default": ""},
            {"name": "--queue-json", "type": "str", "default": ""},
            {"name": "--queue-csv", "type": "str", "default": ""},
        ],
        "main_return": 0,
    },
    "StateMachine": {
        "states": [
            "INIT",
            "PAUSE_FOR_HITL_AUTH",
            "AUTH_VERIFIED",
            "DRAFT_READY",
            "PAUSE_FOR_HITL_FINALIZE",
            "CONTRACT_EFFECTIVE",
            "STOPPED",
        ],
        "normal_path": [
            "INIT",
            "meaning_gate -> RUN/OK",
            "consistency_gate -> RUN/OK",
            "relativity_gate -> RUN/OK",
            "evidence_gate -> RUN/EVIDENCE_OK",
            "auth_request build",
            "critical_missing_gate pass",
            "model_trust_gate",
            "AUTH_VERIFIED (auto auth または bench AUTH_APPROVE 後)",
            "doc_draft -> DRAFT_READY",
            "draft_lint_gate -> RUN/DRAFT_LINT_OK",
            "PAUSE_FOR_HITL_FINALIZE",
            "bench FINALIZE_APPROVE",
            "contract_effect -> CONTRACT_EFFECTIVE",
        ],
        "abnormal_definition": {
            "function": "is_abnormal_run(final_state, sealed)",
            "true_when": [
                "sealed is True",
                "final_state in ['STOPPED', 'PAUSE_FOR_HITL_AUTH', 'PAUSE_FOR_HITL_FINALIZE']",
            ],
        },
    },
    "Gates": {
        "meaning_gate": {
            "decision": "RUN",
            "sealed": False,
            "overrideable": False,
            "reason_code": "OK",
        },
        "consistency_gate": {
            "decision": "RUN",
            "sealed": False,
            "overrideable": False,
            "reason_code": "OK",
        },
        "relativity_gate": {
            "decision": "RUN",
            "sealed": False,
            "overrideable": True,
            "reason_code": "OK",
            "invariant": "sealed must remain False",
        },
        "evidence_gate": {
            "bundle_none": {
                "decision": "PAUSE_FOR_HITL",
                "sealed": False,
                "reason_code": "EVIDENCE_MISSING",
            },
            "schema_invalid": {
                "decision": "PAUSE_FOR_HITL",
                "sealed": False,
                "reason_code": "EVIDENCE_SCHEMA_INVALID",
            },
            "fabricated_any": {
                "decision": "PAUSE_FOR_HITL",
                "sealed": False,
                "reason_code": "EVIDENCE_FABRICATION",
            },
            "ok": {
                "decision": "RUN",
                "sealed": False,
                "reason_code": "EVIDENCE_OK",
            },
        },
        "model_trust_gate": {
            "cooldown_active": "PAUSE_FOR_HITL / TRUST_COOLDOWN_ACTIVE",
            "no_valid_grant": "PAUSE_FOR_HITL / NO_VALID_GRANT",
            "auto_auth_condition": {
                "trust_score_gte": 0.98,
                "approval_streak_gte": 2,
                "requires_valid_grant": True,
                "result": "RUN / AUTO_AUTH_BY_TRUST_AND_GRANT",
            },
            "score_low": "PAUSE_FOR_HITL / TRUST_SCORE_LOW",
        },
        "draft_lint_gate": {
            "legal_binding_claim": "PAUSE_FOR_HITL / SAFETY_LEGAL_BINDING_CLAIM",
            "discrimination_term": "PAUSE_FOR_HITL / SAFETY_DISCRIMINATION_TERM",
            "required_lines_missing": "PAUSE_FOR_HITL / DRAFT_OUT_OF_SCOPE",
            "ok": "RUN / DRAFT_LINT_OK",
        },
        "sealed_emitters": [
            "ethics_gate",
            "acc_gate",
        ],
    },
    "ARL": {
        "format": "JSONL",
        "integrity": {
            "canon_json": "json.dumps(obj, ensure_ascii=False, separators=(',', ':'), sort_keys=True)",
            "row_hash_algo": "HMAC-SHA256",
            "initial_prev_hash": "0" * 64,
            "stored_fields_added": [
                "prev_hash",
                "row_hash",
                "key_id",
                "chain_id",
            ],
            "verify_function": "verify_arl_rows(key, rows)",
        },
        "incident_trigger_conditions": [
            "sealed == True",
            "decision in ('PAUSE_FOR_HITL', 'STOPPED')",
            "layer == 'consistency_gate' and reason_code != 'OK'",
            "reason_code in ('CONSISTENCY_BREAK', 'CRIT_MISSING_REQUIRED_KEYS', 'INVALID_EVENT')",
        ],
        "persistence": {
            "enabled_when": [
                "is_abnormal_run(...) == True",
                "save_arl_on_abnormal == True",
                "arl_out_dir != ''",
                "saved_count < max_arl_files",
            ],
            "filename_pattern": "{incident_id}__{run_id}.arl.jsonl",
            "index_filename": "incident_index.jsonl",
            "counter_filename": "incident_counter.txt",
        },
        "context": {
            "pre_context": "full_context_n rows per run_id",
            "post_context": "post_context_n rows after incident trigger",
            "normal_runs": "FULL rows are generally not persisted unless incident semantics trigger persistence",
        },
    },
    "Results": {
        "top_level_keys": [
            "meta",
            "trust_before",
            "eval_before",
            "abnormal_arl_persistence",
            "runs or runs_sample",
            "trust_after",
            "eval_after",
            "hitl_queue",
        ],
        "meta": {
            "version": "5.1.2",
            "generated_at": "ISO-8601 JST",
            "policy_pack_hash": "POLICY_PACK#SIM#V4_8_2",
            "key_mode": "demo | file | env",
            "key_id": "str",
            "keep_runs": "bool",
            "fabricate_rate": "float | None",
            "seed": "int | None",
        },
        "abnormal_arl_persistence": {
            "enabled": "bool",
            "arl_out_dir": "str",
            "max_arl_files": "int",
            "saved": "int",
            "skipped_by_cap": "int",
            "abnormal_total": "int",
        },
        "run_record": {
            "run_id": "str",
            "final_state": "State",
            "sealed": "bool",
            "runtime_ms": "float",
            "fabricate_evidence": "bool",
            "eval": {
                "multiplier_snapshot": "float",
                "base_score": "float",
                "final_score": "float",
                "reward_granted": "bool",
                "reward_value": "float",
                "clean_completion": "bool",
                "fraud_hits": "list[str]",
            },
            "arl": "list[dict]",
            "trust_after": "TrustState dict",
        },
        "keep_runs_false_contract": {
            "runs_key_present": False,
            "runs_sample_key_present": True,
            "runs_sample_max": "sample_runs (default 5)",
        },
        "hitl_queue": {
            "meta": {
                "version": "str",
                "generated_at": "ISO-8601 str",
                "policy_pack_hash": "str",
                "key_id": "str",
            },
            "counts": {
                "total_runs": "int",
                "by_state": "dict[str, int]",
                "by_reason_code_top20": "dict[str, int]",
                "queue_size": "int",
                "items_kept": "int",
            },
            "items": "list[queue_item]",
        },
        "queue_item": {
            "run_id": "str",
            "final_state": "str",
            "sealed": "bool",
            "primary_reason_code": "str",
            "primary_layer": "str | None",
            "overrideable": "bool | None",
            "final_decider": "str | None",
            "snapshot": {
                "layer": "optional",
                "decision": "optional",
                "reason_code": "optional",
                "missing_keys": "optional",
                "kind": "optional",
                "error": "optional",
                "pattern": "optional",
                "prev_hash": "optional",
                "row_hash": "optional",
            },
        },
    },
    "Determinism": {
        "seed_application": "run_simulation() で seed 指定時に random.seed(int(seed))",
        "fabricate_rule": {
            "fabricate_rate_is_none": "fabricate_this = bool(fabricate)",
            "fabricate_rate_is_set": "fabricate_this = (random.random() < fabricate_rate)",
        },
        "boundary": "同一 seed/fabricate-rate/CLI 引数に加え、同一初期永続状態で決定的再現をサポート",
    },
    "Errors": {
        "fabricate_rate_out_of_range": "ValueError",
        "key_mode_file_missing": "FileNotFoundError",
        "key_mode_env_empty": "ValueError",
        "trust_eval_grants_load_failure": "default/empty にフォールバック",
    },
}
