# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqhCxaX3ML_5LrkB1lOAaEzVwY5MF_yG
"""

# untitled7.py（再掲・保存あり）
import matplotlib.pyplot as plt

rounds = [1, 2, 3, 4, 5]
agentA = [1, 2, 3, 3, 4]
agentB = [2, 2, 2, 3, 3]
agentC = [1, 1, 2, 2, 2]

plt.plot(rounds, agentA, label="Agent A")
plt.plot(rounds, agentB, label="Agent B")
plt.plot(rounds, agentC, label="Agent C")
plt.xlabel("Round")
plt.ylabel("Hierarchy Rank")
plt.title("Hierarchy Rank Transition")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("rank_transition_sample.png")  # ★このファイルが生成される
plt.show()
