# -*- coding: utf-8 -*-
"""
Hierarchy Rank Transition Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5SVRgV6wNFPz8sBGm6heNYIE2DPPNyj
"""

import matplotlib.pyplot as plt  # type: ignore


def plot_hierarchy_rank_transition() -> None:
    """
    ラウンドごとのエージェント階層ランク遷移をグラフ描画し、PNG保存も行う。
    """
    # 仮データ：ラウンドごとの3エージェントの階層ランク
    rounds = [1, 2, 3, 4, 5]
    agentA = [1, 2, 3, 3, 4]
    agentB = [2, 2, 2, 3, 3]
    agentC = [1, 1, 2, 2, 2]

    plt.plot(rounds, agentA, label="Agent A")
    plt.plot(rounds, agentB, label="Agent B")
    plt.plot(rounds, agentC, label="Agent C")
    plt.xlabel("Round")
    plt.ylabel("Hierarchy Rank")
    plt.title("Hierarchy Rank Transition")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("rank_transition_sample.png")
    plt.show()


if __name__ == "__main__":
    plot_hierarchy_rank_transition()
