# -*- coding: utf-8 -*-
"""Untitled7.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1l5SVRgV6wNFPz8sBGm6heNYIE2DPPNyj
"""

import matplotlib.pyplot as plt

# 階層ランクのグラフ
rounds = [1, 2, 3, 4, 5]
agentA = [1, 2, 3, 3, 4]
agentB = [2, 2, 2, 3, 3]
agentC = [1, 1, 2, 2, 2]

plt.plot(rounds, agentA, label="Agent A")
plt.plot(rounds, agentB, label="Agent B")
plt.plot(rounds, agentC, label="Agent C")
plt.xlabel("Round")
plt.ylabel("Hierarchy Rank")
plt.title("Hierarchy Rank Transition")
plt.legend()
plt.savefig("rank_transition_sample.png")  # カレントディレクトリに保存
plt.show()

# 感情値のグラフ
rounds = [1, 2, 3, 4, 5]
emotionA = [0.2, 0.4, 0.7, 0.3, 0.1]
emotionB = [0.5, 0.6, 0.8, 0.5, 0.4]

plt.plot(rounds, emotionA, label="Agent A Emotion")
plt.plot(rounds, emotionB, label="Agent B Emotion")
plt.xlabel("Round")
plt.ylabel("Emotion Level")
plt.title("Emotion Dynamics")
plt.legend()
plt.savefig("emotion_dynamics_sample.png")
plt.show()